import React, { useState, useEffect } from 'react';

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home({ data }) {
  const recipes = data.recipes;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      </main>
    </div>
  )
}



export async function getStaticProps() {
    fetch('https://jsonplaceholder.typicode.com/users')
    .then(res => res.json())
    .then(data => console.log(data))
  return {
    props: {
      data: {
        recipes: [
          { title: 'Pineapple shake' },
          { title: 'Mango shake' },
          { title: 'Milk shake' }
        ]
      }
    }
  }
}